type: dpmsolver_multistep
set_model_outputs: True
target: inference.libs.scheduler.dpmsolver_multistep.DPMSolverMultistepScheduler
params:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "scaled_linear"
  trained_betas: None
  solver_order: 2
  prediction_type: "epsilon"
  thresholding: False
  dynamic_thresholding_ratio: 0.995
  sample_max_value: 1.0
  algorithm_type: "dpmsolver++"
  solver_type: "midpoint"
  lower_order_final: True
  use_karras_sigmas: False
  variance_type: None
  timestep_spacing: "linspace"
  steps_offset: 0
